import {
  CircleHelp,
  Phone,
  MessageCircleReply,
  CheckCircle,
} from "lucide-react";

export type Lead = {
  id: string;
  name: string;
  title: string;
  avatar: {
    src: string;
    fallback: string;
  };
  email: string;
  company: string;
  campaignName: string;
  activity: number;
  status: "Pending" | "Contacted" | "Responded" | "Converted";
  lastContactDate: Date;
};

export const statusStyles = {
  Pending: {
    icon: CircleHelp,
    color: "bg-gray-200 text-gray-800 border-gray-300",
  },
  Contacted: {
    icon: Phone,
    color: "bg-blue-100 text-blue-800 border-blue-200",
  },
  Responded: {
    icon: MessageCircleReply,
    color: "bg-orange-100 text-orange-800 border-orange-200",
  },
  Converted: {
    icon: CheckCircle,
    color: "bg-green-100 text-green-800 border-green-200",
  },
};

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Alia Sharma",
    title: "Marketing Head",
    avatar: { src: "https://i.pravatar.cc/150?u=10", fallback: "AS" },
    email: "alia.s@example.com",
    company: "Innovate Inc.",
    campaignName: "Q4 Launch",
    activity: 3,
    status: "Responded",
    lastContactDate: new Date("2025-09-05"),
  },
  {
    id: "2",
    name: "Ben Carter",
    title: "Sales Director",
    avatar: { src: "https://i.pravatar.cc/150?u=11", fallback: "BC" },
    email: "ben.c@example.com",
    company: "Solutions Co.",
    campaignName: "Lead Gen 2025",
    activity: 4,
    status: "Converted",
    lastContactDate: new Date("2025-09-02"),
  },
  {
    id: "3",
    name: "Catherine D'souza",
    title: "CEO",
    avatar: { src: "https://i.pravatar.cc/150?u=12", fallback: "CD" },
    email: "c.dsouza@example.com",
    company: "Global Tech",
    campaignName: "Enterprise Outreach",
    activity: 2,
    status: "Contacted",
    lastContactDate: new Date("2025-09-07"),
  },
  {
    id: "4",
    name: "David Lee",
    title: "Product Manager",
    avatar: { src: "", fallback: "DL" },
    email: "david.lee@example.com",
    company: "Innovate Inc.",
    campaignName: "Q4 Launch",
    activity: 1,
    status: "Pending",
    lastContactDate: new Date("2025-08-20"),
  },
  {
    id: "5",
    name: "Eva Green",
    title: "HR Manager",
    avatar: { src: "https://i.pravatar.cc/150?u=14", fallback: "EG" },
    email: "eva.g@example.com",
    company: "People First",
    campaignName: "Hiring Drive",
    activity: 3,
    status: "Responded",
    lastContactDate: new Date("2025-09-06"),
  },
  {
    id: "6",
    name: "Frank Miller",
    title: "CTO",
    avatar: { src: "https://i.pravatar.cc/150?u=15", fallback: "FM" },
    email: "frank.m@example.com",
    company: "Global Tech",
    campaignName: "Enterprise Outreach",
    activity: 0,
    status: "Pending",
    lastContactDate: new Date("2025-08-15"),
  },
  {
    id: "7",
    name: "Grace Hopper",
    title: "Software Engineer",
    avatar: { src: "https://i.pravatar.cc/150?u=16", fallback: "GH" },
    email: "grace.h@example.com",
    company: "Tech Solutions",
    campaignName: "Dev Outreach",
    activity: 4,
    status: "Contacted",
    lastContactDate: new Date("2025-09-01"),
  },
  {
    id: "8",
    name: "Henry Ford",
    title: "Operations Lead",
    avatar: { src: "https://i.pravatar.cc/150?u=17", fallback: "HF" },
    email: "henry.f@example.com",
    company: "Logistics Pro",
    campaignName: "Partnership Drive",
    activity: 2,
    status: "Responded",
    lastContactDate: new Date("2025-08-28"),
  },
  {
    id: "9",
    name: "Isabel Martinez",
    title: "Financial Analyst",
    avatar: { src: "https://i.pravatar.cc/150?u=18", fallback: "IM" },
    email: "isabel.m@example.com",
    company: "Finance Plus",
    campaignName: "Investment Series",
    activity: 3,
    status: "Converted",
    lastContactDate: new Date("2025-09-10"),
  },
  {
    id: "10",
    name: "Jack Thompson",
    title: "VP Sales",
    avatar: { src: "https://i.pravatar.cc/150?u=19", fallback: "JT" },
    email: "jack.t@example.com",
    company: "Growth Corp",
    campaignName: "Scale Up 2025",
    activity: 5,
    status: "Responded",
    lastContactDate: new Date("2025-09-08"),
  },
  {
    id: "11",
    name: "Kelly Johnson",
    title: "Design Lead",
    avatar: { src: "https://i.pravatar.cc/150?u=20", fallback: "KJ" },
    email: "kelly.j@example.com",
    company: "Creative Studios",
    campaignName: "Brand Refresh",
    activity: 2,
    status: "Contacted",
    lastContactDate: new Date("2025-09-04"),
  },
  {
    id: "12",
    name: "Lucas Brown",
    title: "Data Scientist",
    avatar: { src: "https://i.pravatar.cc/150?u=21", fallback: "LB" },
    email: "lucas.b@example.com",
    company: "Analytics Hub",
    campaignName: "Data Insights",
    activity: 1,
    status: "Pending",
    lastContactDate: new Date("2025-08-25"),
  },
  {
    id: "13",
    name: "Maria Rodriguez",
    title: "Account Manager",
    avatar: { src: "https://i.pravatar.cc/150?u=22", fallback: "MR" },
    email: "maria.r@example.com",
    company: "Client Success",
    campaignName: "Retention Drive",
    activity: 4,
    status: "Converted",
    lastContactDate: new Date("2025-09-09"),
  },
  {
    id: "14",
    name: "Nathan Clark",
    title: "DevOps Engineer",
    avatar: { src: "https://i.pravatar.cc/150?u=23", fallback: "NC" },
    email: "nathan.c@example.com",
    company: "Cloud Systems",
    campaignName: "Infrastructure 2025",
    activity: 3,
    status: "Responded",
    lastContactDate: new Date("2025-09-03"),
  },
  {
    id: "15",
    name: "Olivia Davis",
    title: "Marketing Director",
    avatar: { src: "https://i.pravatar.cc/150?u=24", fallback: "OD" },
    email: "olivia.d@example.com",
    company: "Brand Builders",
    campaignName: "Digital Transform",
    activity: 2,
    status: "Contacted",
    lastContactDate: new Date("2025-08-30"),
  },
  {
    id: "16",
    name: "Peter Wilson",
    title: "Chief Strategy Officer",
    avatar: { src: "https://i.pravatar.cc/150?u=25", fallback: "PW" },
    email: "peter.w@example.com",
    company: "Strategic Partners",
    campaignName: "Growth Strategy",
    activity: 0,
    status: "Pending",
    lastContactDate: new Date("2025-08-18"),
  },
  {
    id: "17",
    name: "Quinn Taylor",
    title: "UX Designer",
    avatar: { src: "https://i.pravatar.cc/150?u=26", fallback: "QT" },
    email: "quinn.t@example.com",
    company: "Design Co.",
    campaignName: "User Experience",
    activity: 5,
    status: "Converted",
    lastContactDate: new Date("2025-09-11"),
  },
  {
    id: "18",
    name: "Rachel Green",
    title: "Business Analyst",
    avatar: { src: "https://i.pravatar.cc/150?u=27", fallback: "RG" },
    email: "rachel.g@example.com",
    company: "Business Intelligence",
    campaignName: "Process Optimization",
    activity: 3,
    status: "Responded",
    lastContactDate: new Date("2025-09-05"),
  },
  {
    id: "19",
    name: "Samuel Anderson",
    title: "Security Engineer",
    avatar: { src: "https://i.pravatar.cc/150?u=28", fallback: "SA" },
    email: "samuel.a@example.com",
    company: "SecureTech",
    campaignName: "Cybersecurity Focus",
    activity: 1,
    status: "Contacted",
    lastContactDate: new Date("2025-08-27"),
  },
  {
    id: "20",
    name: "Tina White",
    title: "Operations Manager",
    avatar: { src: "https://i.pravatar.cc/150?u=29", fallback: "TW" },
    email: "tina.w@example.com",
    company: "Efficiency Corp",
    campaignName: "Workflow Optimization",
    activity: 4,
    status: "Converted",
    lastContactDate: new Date("2025-09-07"),
  },
  {
    id: "21",
    name: "Victor Kumar",
    title: "AI Research Lead",
    avatar: { src: "https://i.pravatar.cc/150?u=30", fallback: "VK" },
    email: "victor.k@example.com",
    company: "AI Innovations",
    campaignName: "Future Tech",
    activity: 2,
    status: "Pending",
    lastContactDate: new Date("2025-08-22"),
  },
  {
    id: "22",
    name: "Wendy Phillips",
    title: "Content Manager",
    avatar: { src: "https://i.pravatar.cc/150?u=31", fallback: "WP" },
    email: "wendy.p@example.com",
    company: "Content Creators",
    campaignName: "Content Strategy",
    activity: 3,
    status: "Responded",
    lastContactDate: new Date("2025-09-06"),
  },
  {
    id: "23",
    name: "Xavier Chen",
    title: "Mobile Developer",
    avatar: { src: "https://i.pravatar.cc/150?u=32", fallback: "XC" },
    email: "xavier.c@example.com",
    company: "Mobile First",
    campaignName: "App Development",
    activity: 4,
    status: "Contacted",
    lastContactDate: new Date("2025-09-01"),
  },
  {
    id: "24",
    name: "Yuki Tanaka",
    title: "Quality Assurance Lead",
    avatar: { src: "https://i.pravatar.cc/150?u=33", fallback: "YT" },
    email: "yuki.t@example.com",
    company: "Quality Systems",
    campaignName: "QA Excellence",
    activity: 1,
    status: "Pending",
    lastContactDate: new Date("2025-08-19"),
  },
  {
    id: "25",
    name: "Zoe Mitchell",
    title: "Customer Success Manager",
    avatar: { src: "https://i.pravatar.cc/150?u=34", fallback: "ZM" },
    email: "zoe.m@example.com",
    company: "Customer Care Plus",
    campaignName: "Success Stories",
    activity: 5,
    status: "Converted",
    lastContactDate: new Date("2025-09-12"),
  },
  {
    id: "26",
    name: "Alex Rivera",
    title: "Blockchain Developer",
    avatar: { src: "https://i.pravatar.cc/150?u=35", fallback: "AR" },
    email: "alex.r@example.com",
    company: "Crypto Solutions",
    campaignName: "Web3 Initiative",
    activity: 2,
    status: "Responded",
    lastContactDate: new Date("2025-08-31"),
  },
  {
    id: "27",
    name: "Blake Sanders",
    title: "Growth Hacker",
    avatar: { src: "https://i.pravatar.cc/150?u=36", fallback: "BS" },
    email: "blake.s@example.com",
    company: "Growth Labs",
    campaignName: "Viral Marketing",
    activity: 3,
    status: "Contacted",
    lastContactDate: new Date("2025-09-04"),
  },
  {
    id: "28",
    name: "Chloe Adams",
    title: "Partnership Manager",
    avatar: { src: "https://i.pravatar.cc/150?u=37", fallback: "CA" },
    email: "chloe.a@example.com",
    company: "Alliance Networks",
    campaignName: "Strategic Partnerships",
    activity: 0,
    status: "Pending",
    lastContactDate: new Date("2025-08-16"),
  },
];
